name: 'Upload AAB and download APK'
description: 'Upload AAB and download APK, Google Play Console'
inputs:
  service-account-credential-base64:
    description: 'Service account credential base64'
    required: true
  package-name:
    description: 'Package name'
    required: true
  aab-file-path:
    description: 'aab file path'
    required: true
outputs:
  universal-apk-file-path:
    description: 'Universal apk file path'
    value: ${{ steps.upload-aab-and-download-apk.outputs.universal-apk-file-path }}
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
          ls -al ${{ github.action_path }}
          echo ${{ github.action_path }}
          pwd
          cd ${{ github.action_path }}

    - uses: actions/setup-python@v3
      with:
          python-version: '3.8'
          cache: 'pip'

